name: CI
on:
  push:
    branches: [patch]
  pull_request:
    branches: [patch]

jobs:
  unit-tests:
    name: Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - uses: actions/checkout@v3
    - run: go version
    - run: go vet .
    - run: go test -v -cover -vet=off .
