name: build

on:
  push:
    branches: [sideline, patch]
  pull_request:
    branches: [sideline, patch]

jobs:
  audit:
    strategy:
      matrix:
        go: [1.19.x, 1.20.x, 1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go vet ./...
      - run: go test -vet=off ./...
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
